### ISSUE TITLE
pin_enter state transition incomplete

### ISSUE THREAD

**Issue by crinq** [hyperelastic/nc-servoterm#3]
[pin_enter()](https://github.com/hyperelastic/nc-servoterm/blob/master/tui.c#L147) should:
1. redraw the menu
2. clear shell_buffer 
3. reset hal_pins_menu selection 

2 and 3 are missing/not working.

**Comment by hyperelastic** [comment]
Hi @crinq. In devel I changed the behaviour of pin_enter(). Workflow now is for example: 

1. Start in empty shell window.
2. Transition to pins menu window with the down arrow.
3. Navigate to "rev0.in" pin using pgdown/pgup and up/down arrows.
4. Press enter. This moves text in shell window and moves cursor to it's end.
5. Edit shell buffer by hand, writing " = ".
6. Transition to pins menu again with down arrow.
7. Navigate to pin "sim0.msin".
8. Press enter to add to shell buffer and transition to shell window.
9. Press enter again to send "rev0.in = sim0.msin" to stmbl.

To achieve this you can also just start in shell window, write "rev0.in = sim0.msin" and press enter.

**Comment by hyperelastic** [comment]
This is now in master too. I also added shell history.
